services:
  mycoursereviews:
    image: mycoursereviews:latest
    container_name: mycoursereviews
    env_file:
      - .env.local
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=3200
      - COURSES_DB_PATH=/data/courses-api/local.sqlite3
    volumes:
      - ./courses-api-data:/data/courses-api:ro
    ports:
      - 3200:3200
    networks:
      - csclub
    extra_hosts:
      - "auth.csclub.org.au:host-gateway"
      - "courses-api.csclub.org.au:host-gateway"

networks:
  csclub:
    external: true
