services:
  mycoursereviews:
    build:
      context: .
      dockerfile: Dockerfile
    image: mycoursereviews:latest
    container_name: mycoursereviews
    env_file:
      - .env.local
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=3200
      - DATABASE_URL=postgresql://postgres:postgres@mycoursereviews-db:5432/mycoursereviews
      - REDIS_URL=redis://mycoursereviews-cache:6379
    ports:
      - 3200:3200
    depends_on:
      - mycoursereviews-db
      - mycoursereviews-cache
    networks:
      - csclub
    extra_hosts:
      - "auth.csclub.org.au:host-gateway"

volumes:
  pgdata:
  redisdata:

networks:
  csclub:
    external: true
