services:
  mycoursereviews-keycloak:
    container_name: mycoursereviews-keycloak
    image: quay.io/keycloak/keycloak:26.6.1
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:8080']
    environment:
      - DB_VENDOR=h2
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json:ro
    command: ['start-dev', '--import-realm']
    networks:
      - csclub

  mycoursereviews-db:
    image: postgres:18-alpine
    container_name: mycoursereviews-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mycoursereviews
    ports:
      - 5432:5432
    volumes:
      - pgdata-dev:/var/lib/postgresql
    networks:
      - csclub

  mycoursereviews:
    container_name: mycoursereviews
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    env_file:
      - .env.dev.docker
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=3200
    ports:
      - 3200:3200
    volumes:
      - .:/app
      - /app/node_modules
      - ../courses-api/src:/data/courses-api:ro
    depends_on:
      - mycoursereviews-db
    command: sh -c "CI=true pnpm install && pnpm run db:push && pnpm run dev"
    networks:
      - csclub

volumes:
  pgdata-dev:

networks:
  csclub:
