name: Linting Checks
on:
  workflow_call:

permissions:
  contents: read

jobs:
  es-lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # v4
        with:
          version: 11
      - run: pnpm install
      - run: pnpm run lint
