name: Unit Tests
on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 26

      - name: Install pnpm
        run: npm install -g pnpm@11

      - name: Install dependencies
        run: pnpm install

      - name: Run native unit tests
        run: pnpm run test:unit
